### ISSUE TITLE
Release 3.14 Checklist

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#1468]
JDN release version - [3.14.2](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.2)

- [x] DEV team should create the release build @Iogsotot 
- [x] DEV team should check, that the backend version is correct and working smoothly @Ekaterina-Zykova 
- [x] DEV team should update the compatibility matrix @Iogsotot
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/69271564/FAQ#Version-compatibility-list
- [ ] Product Owner should conduct acceptance testing @savinovava 
- [x] UX team should conduct acceptance testing @SemyonKuznetsov 
- [ ] QA team should conduct regress testing @Lisa5876 
- [ ] BA team should update the release notes of the plugin in Google Chrome extensions @savinovava  
- [ ] DEV team publishes the plugin to the Chrome Web Store @savinovava

**Comment by SemyonKuznetsov** [comment]
@AlexeyGirin для скайп-чата или релиз ноутс


Dear friends!
I'm pleased to announce that we've just released a new version 3.14 of the JDN plugin.
https://chrome.google.com/webstore/detail/jdn/dldagjdnndapekahhbpeemjifghccldg/related

What's New:
* Added the «Vividus» framework, with «Selenium» and «Selenide» already in development.
* Introduced a new «FindBy» annotation.
* Now you can create an Empty Page Object and manually select the necessary locators from the coverage.
* Added new shortcuts using Enter and Esc keys in modal windows, as well as CTRL+Z for text input editing.
* Group functions include Delete, Restore, and Advanced Calculation. This works on site coverage too!
* Bug fixes and many other small improvements
__
We always welcome your feedback. We always appreciate your feedback, feel free to write to us.
