### ISSUE TITLE
Release 3.15 Checklist

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#1615]
JDN release version - [3.15](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.0)
- [x]  DEV team should create the release build @Iogsotot
- [x]  DEV team should check, that the backend version is correct and working smoothly @ivnglkv 
- [x]  DEV team should update the compatibility matrix @Iogsotot
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/69271564/FAQ#Version-compatibility-list
- [x]  Product Owner should conduct acceptance testing @AlexeyGirin 
- [x]  UX team should conduct acceptance testing @SemyonKuznetsov
- [x]  QA team should conduct regress testing @mobilisf 
- [x]  BA team should update the release notes of the plugin in Google Chrome extensions @savinovava
- [x]  DEV team publishes the plugin to the Chrome Web Store @savinovava
