### ISSUE TITLE
Release 3.16 Checklist

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1749]
JDN release version - [3.15](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.0)
- [ ]  DEV team should create the release build @Iogsotot
- [ ]  DEV team should check, that the backend version is correct and working smoothly @ivnglkv 
- [ ]  DEV team should update the compatibility matrix @Iogsotot
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/69271564/FAQ#Version-compatibility-list
- [ ]  Product Owner should conduct acceptance testing @AlexeyGirin 
- [ ]  UX team should conduct acceptance testing @SemyonKuznetsov
- [ ]  QA team should conduct regress testing @mobilisf 
- [ ]  BA team should update the release notes of the plugin in Google Chrome extensions @savinovava
- [ ]  DEV team publishes the plugin to the Chrome Web Store @savinovava
