### ISSUE TITLE
[Low] small visual bugs

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#755]
**так как я не очень понимаю насколько большие эти таски в исправлении, их можно будет выделять в отдельные задачи, всё что мне кажется небольшим в имплементации я складываю сюда**

- [x] при появлении тэга элемент становиться больше, должен быть фиксированный по высоте размер полоски с чекбоксом и тэгом селекта. сейчас элемент 22px по высоте 
<img  src="https://user-images.githubusercontent.com/101407186/199456092-c8b1a8c9-775a-4106-9fd7-288f2df0846f.mov">

<img width="936" alt="Снимок экрана 2022-11-14 в 15 54 48" src="https://user-images.githubusercontent.com/101407186/201665475-eb02d237-df90-4dff-8805-d045e4c6fde7.png">

- [x]  Пункты должны быть нумерованы как 1 2 3?
<img height="200" src="https://user-images.githubusercontent.com/101407186/199456314-d9c3af04-990e-4ec7-845d-f69505f9d248.png">

- [x] у кнопок снизу нет отступа, сделать 16px [figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7169%3A355078&t=o4Cxg4r0aFEEmbvN-4)
<img width="294" alt="Снимок экрана 2023-01-20 в 13 40 14" src="https://user-images.githubusercontent.com/101407186/213675976-b333eae2-ebd1-4d57-8f8d-c79d756242cb.png">

- [x] #984
<img height="400" src="https://user-images.githubusercontent.com/101407186/199466596-382376ae-037d-4e62-8d5b-91ad9ee429fe.png">

- [x] возможный баг с анимацией выбора
<img width="500" alt="Снимок экрана 2022-11-02 в 13 29 34" src="https://user-images.githubusercontent.com/101407186/200321072-743dfb9a-aead-4bdb-9f8b-2a2bf48a897c.mov">

- [x] #1016 обновить текст и добавить для текста обязательный отступ от границы блока по 16px с каждой стороны
<img width="464" alt="Снимок экрана 2022-11-07 в 16 45 23" src="https://user-images.githubusercontent.com/101407186/200326001-f4694948-2dae-453d-b116-2a1c68ffe6ae.png">
<img width="614" alt="Снимок экрана 2022-11-14 в 16 47 55" src="https://user-images.githubusercontent.com/101407186/201676268-3e0b9e52-644c-4718-9f33-267c7d21b122.png">

- [x] #846 поменять текст последних строк в меню на bring to front & send to back, это как устойчивое выражение
<img height="400" src="https://user-images.githubusercontent.com/101407186/200805748-8879097b-db71-4ead-9921-3216c1f8d8eb.png">

- [x] #1012 добавить цветовой статус hover для элемента строки page object аналогично строкам локатора в задаче #766

https://user-images.githubusercontent.com/101407186/201664511-3b42d6ad-8b44-4e85-8b6f-794501d86525.mov

- [x] #1020
<img width="497" alt="Снимок экрана 2022-11-15 в 11 56 06" src="https://user-images.githubusercontent.com/101407186/201874886-df832893-600f-4fba-93b6-bcafc597a09c.png">

- [x]  (in progress) поправить размеры иконок с 14 до 16 (чтобы выровнять с текстом) и выровнять чекбоксы

- [x] #1017
<img width="202" alt="Снимок экрана 2022-12-20 в 12 47 21" src="https://user-images.githubusercontent.com/101407186/208636236-eb54d88d-5bda-4077-a1e5-a24197575cd6.png">

- [x] #1019
<img width="1091" alt="Снимок экрана 2022-12-20 в 12 48 10" src="https://user-images.githubusercontent.com/101407186/208636419-b72d00ee-395b-4d6b-a428-cb69d3f2b30f.png">

**Comment by SemyonKuznetsov** [comment]
декомпозировал на другие задачи
